package garden.ephemeral.glyphplay.unicode

import com.ibm.icu.lang.UProperty
import com.ibm.icu.lang.UScript
import java.util.BitSet

enum class UnicodeScript(override val icuValue: Int, val code: String, val codeAliases: List<String> = emptyList()) :
    UnicodeValueEnum<UnicodeScript> {

    COMMON(UScript.COMMON, "Zyyy"),

    // "Code for inherited script", for non-spacing combining marks; also Qaai
    INHERITED(UScript.INHERITED, "Zinh"),

    ARABIC(UScript.ARABIC, "Arab"),
    ARMENIAN(UScript.ARMENIAN, "Armn"),
    BENGALI(UScript.BENGALI, "Beng"),
    BOPOMOFO(UScript.BOPOMOFO, "Bopo"),
    CHEROKEE(UScript.CHEROKEE, "Cher"),
    COPTIC(UScript.COPTIC, "Qaac"),
    CYRILLIC(UScript.CYRILLIC, "Cyrl", listOf("Cyrs")),
    DESERET(UScript.DESERET, "Dsrt"),
    DEVANAGARI(UScript.DEVANAGARI, "Deva"),
    ETHIOPIC(UScript.ETHIOPIC, "Ethi"),
    GEORGIAN(UScript.GEORGIAN, "Geor", listOf("Geon", "Geoa")),
    GOTHIC(UScript.GOTHIC, "Goth"),
    GREEK(UScript.GREEK, "Grek"),
    GUJARATI(UScript.GUJARATI, "Gujr"),
    GURMUKHI(UScript.GURMUKHI, "Guru"),
    HAN(UScript.HAN, "Hani"),
    HANGUL(UScript.HANGUL, "Hang"),
    HEBREW(UScript.HEBREW, "Hebr"),
    HIRAGANA(UScript.HIRAGANA, "Hira"),
    KANNADA(UScript.KANNADA, "Knda"),
    KATAKANA(UScript.KATAKANA, "Kana"),
    KHMER(UScript.KHMER, "Khmr"),
    LAO(UScript.LAO, "Laoo"),
    LATIN(UScript.LATIN, "Latn", listOf("Latf", "Latg")),
    MALAYALAM(UScript.MALAYALAM, "Mlym"),
    MONGOLIAN(UScript.MONGOLIAN, "Mong"),
    MYANMAR(UScript.MYANMAR, "Mymr"),
    OGHAM(UScript.OGHAM, "Ogam"),
    OLD_ITALIC(UScript.OLD_ITALIC, "Ital"),
    ORIYA(UScript.ORIYA, "Orya"),
    RUNIC(UScript.RUNIC, "Runr"),
    SINHALA(UScript.SINHALA, "Sinh"),
    SYRIAC(UScript.SYRIAC, "Syrc", listOf("Syrj", "Syrn", "Syre")),
    TAMIL(UScript.TAMIL, "Taml"),
    TELUGU(UScript.TELUGU, "Telu"),
    THAANA(UScript.THAANA, "Thaa"),
    THAI(UScript.THAI, "Thai"),
    TIBETAN(UScript.TIBETAN, "Tibt"),
    CANADIAN_ABORIGINAL(UScript.CANADIAN_ABORIGINAL, "Cans"),
    YI(UScript.YI, "Yiii"),
    TAGALOG(UScript.TAGALOG, "Tglg"),
    HANUNOO(UScript.HANUNOO, "Hano"),
    BUHID(UScript.BUHID, "Buhd"),
    TAGBANWA(UScript.TAGBANWA, "Tagb"),
    BRAILLE(UScript.BRAILLE, "Brai"),
    CYPRIOT(UScript.CYPRIOT, "Cprt"),
    LIMBU(UScript.LIMBU, "Limb"),
    LINEAR_B(UScript.LINEAR_B, "Linb"),
    OSMANYA(UScript.OSMANYA, "Osma"),
    SHAVIAN(UScript.SHAVIAN, "Shaw"),
    TAI_LE(UScript.TAI_LE, "Tale"),
    UGARITIC(UScript.UGARITIC, "Ugar"),
    KATAKANA_OR_HIRAGANA(UScript.KATAKANA_OR_HIRAGANA, "Hrkt"),
    BUGINESE(UScript.BUGINESE, "Bugi"),
    GLAGOLITIC(UScript.GLAGOLITIC, "Glag"),
    KHAROSHTHI(UScript.KHAROSHTHI, "Khar"),
    SYLOTI_NAGRI(UScript.SYLOTI_NAGRI, "Sylo"),
    NEW_TAI_LUE(UScript.NEW_TAI_LUE, "Talu"),
    TIFINAGH(UScript.TIFINAGH, "Tfng"),
    OLD_PERSIAN(UScript.OLD_PERSIAN, "Xpeo"),
    BALINESE(UScript.BALINESE, "Bali"),
    BATAK(UScript.BATAK, "Batk"),
    BLISSYMBOLS(UScript.BLISSYMBOLS, "Blis"),
    BRAHMI(UScript.BRAHMI, "Brah"),
    CHAM(UScript.CHAM, "Cham"),
    CIRTH(UScript.CIRTH, "Cirt"),
    OLD_CHURCH_SLAVONIC_CYRILLIC(UScript.OLD_CHURCH_SLAVONIC_CYRILLIC, "Cyrs"),
    DEMOTIC_EGYPTIAN(UScript.DEMOTIC_EGYPTIAN, "Egyd"),
    HIERATIC_EGYPTIAN(UScript.HIERATIC_EGYPTIAN, "Egyh"),
    EGYPTIAN_HIEROGLYPHS(UScript.EGYPTIAN_HIEROGLYPHS, "Egyp"),
    KHUTSURI(UScript.KHUTSURI, "Geok"),
    SIMPLIFIED_HAN(UScript.SIMPLIFIED_HAN, "Hans"),
    TRADITIONAL_HAN(UScript.TRADITIONAL_HAN, "Hant"),
    PAHAWH_HMONG(UScript.PAHAWH_HMONG, "Hmng"),
    OLD_HUNGARIAN(UScript.OLD_HUNGARIAN, "Hung"),
    HARAPPAN_INDUS(UScript.HARAPPAN_INDUS, "Inds"),
    JAVANESE(UScript.JAVANESE, "Java"),
    KAYAH_LI(UScript.KAYAH_LI, "Kali"),
    LATIN_FRAKTUR(UScript.LATIN_FRAKTUR, "Latf"),
    LATIN_GAELIC(UScript.LATIN_GAELIC, "Latg"),
    LEPCHA(UScript.LEPCHA, "Lepc"),
    LINEAR_A(UScript.LINEAR_A, "Lina"),
    MANDAIC(UScript.MANDAIC, "Mand"),
    MAYAN_HIEROGLYPHS(UScript.MAYAN_HIEROGLYPHS, "Maya"),
    MEROITIC_HIEROGLYPHS(UScript.MEROITIC_HIEROGLYPHS, "Mero"),
    NKO(UScript.NKO, "Nkoo"),
    ORKHON(UScript.ORKHON, "Orkh"),
    OLD_PERMIC(UScript.OLD_PERMIC, "Perm"),
    PHAGS_PA(UScript.PHAGS_PA, "Phag"),
    PHOENICIAN(UScript.PHOENICIAN, "Phnx"),
    MIAO(UScript.MIAO, "Plrd"),
    RONGORONGO(UScript.RONGORONGO, "Roro"),
    SARATI(UScript.SARATI, "Sara"),
    ESTRANGELO_SYRIAC(UScript.ESTRANGELO_SYRIAC, "Syre"),
    WESTERN_SYRIAC(UScript.WESTERN_SYRIAC, "Syrj"),
    EASTERN_SYRIAC(UScript.EASTERN_SYRIAC, "Syrn"),
    TENGWAR(UScript.TENGWAR, "Teng"),
    VAI(UScript.VAI, "Vaii"),
    VISIBLE_SPEECH(UScript.VISIBLE_SPEECH, "Visp"),
    CUNEIFORM(UScript.CUNEIFORM, "Xsux"),
    UNWRITTEN_LANGUAGES(UScript.UNWRITTEN_LANGUAGES, "Zxxx"),

    // Code for uncoded script", for unassigned code points
    UNKNOWN(UScript.UNKNOWN, "Zzzz"),

    CARIAN(UScript.CARIAN, "Cari"),
    JAPANESE(UScript.JAPANESE, "Jpan"),
    LANNA(UScript.LANNA, "Lana"),
    LYCIAN(UScript.LYCIAN, "Lyci"),
    LYDIAN(UScript.LYDIAN, "Lydi"),
    OL_CHIKI(UScript.OL_CHIKI, "Olck"),
    REJANG(UScript.REJANG, "Rjng"),
    SAURASHTRA(UScript.SAURASHTRA, "Saur"),
    SIGN_WRITING(UScript.SIGN_WRITING, "Sgnw"),
    SUNDANESE(UScript.SUNDANESE, "Sund"),
    MOON(UScript.MOON, "Moon"),
    MEITEI_MAYEK(UScript.MEITEI_MAYEK, "Mtei"),
    IMPERIAL_ARAMAIC(UScript.IMPERIAL_ARAMAIC, "Armi"),
    AVESTAN(UScript.AVESTAN, "Avst"),
    CHAKMA(UScript.CHAKMA, "Cakm"),
    KOREAN(UScript.KOREAN, "Kore"),
    KAITHI(UScript.KAITHI, "Kthi"),
    MANICHAEAN(UScript.MANICHAEAN, "Mani"),
    INSCRIPTIONAL_PAHLAVI(UScript.INSCRIPTIONAL_PAHLAVI, "Phli"),
    PSALTER_PAHLAVI(UScript.PSALTER_PAHLAVI, "Phlp"),
    BOOK_PAHLAVI(UScript.BOOK_PAHLAVI, "Phlv"),
    INSCRIPTIONAL_PARTHIAN(UScript.INSCRIPTIONAL_PARTHIAN, "Prti"),
    SAMARITAN(UScript.SAMARITAN, "Samr"),
    TAI_VIET(UScript.TAI_VIET, "Tavt"),
    MATHEMATICAL_NOTATION(UScript.MATHEMATICAL_NOTATION, "Zmth"),
    SYMBOLS(UScript.SYMBOLS, "Zsym"),
    BAMUM(UScript.BAMUM, "Bamu"),
    LISU(UScript.LISU, "Lisu"),
    NAKHI_GEBA(UScript.NAKHI_GEBA, "Nkgb"),
    OLD_SOUTH_ARABIAN(UScript.OLD_SOUTH_ARABIAN, "Sarb"),
    BASSA_VAH(UScript.BASSA_VAH, "Bass"),
    DUPLOYAN(UScript.DUPLOYAN, "Dupl"),
    ELBASAN(UScript.ELBASAN, "Elba"),
    GRANTHA(UScript.GRANTHA, "Gran"),
    KPELLE(UScript.KPELLE, "Kpel"),
    LOMA(UScript.LOMA, "Loma"),
    MENDE(UScript.MENDE, "Mend"),
    MEROITIC_CURSIVE(UScript.MEROITIC_CURSIVE, "Merc"),
    OLD_NORTH_ARABIAN(UScript.OLD_NORTH_ARABIAN, "Narb"),
    NABATAEAN(UScript.NABATAEAN, "Nbat"),
    PALMYRENE(UScript.PALMYRENE, "Palm"),
    KHUDAWADI(UScript.KHUDAWADI, "Sind"),
    WARANG_CITI(UScript.WARANG_CITI, "Wara"),
    AFAKA(UScript.AFAKA, "Afak"),
    JURCHEN(UScript.JURCHEN, "Jurc"),
    MRO(UScript.MRO, "Mroo"),
    NUSHU(UScript.NUSHU, "Nshu"),
    SHARADA(UScript.SHARADA, "Shrd"),
    SORA_SOMPENG(UScript.SORA_SOMPENG, "Sora"),
    TAKRI(UScript.TAKRI, "Takr"),
    TANGUT(UScript.TANGUT, "Tang"),
    WOLEAI(UScript.WOLEAI, "Wole"),
    ANATOLIAN_HIEROGLYPHS(UScript.ANATOLIAN_HIEROGLYPHS, "Hluw"),
    KHOJKI(UScript.KHOJKI, "Khoj"),
    TIRHUTA(UScript.TIRHUTA, "Tirh"),
    CAUCASIAN_ALBANIAN(UScript.CAUCASIAN_ALBANIAN, "Aghb"),
    MAHAJANI(UScript.MAHAJANI, "Mahj"),
    AHOM(UScript.AHOM, "Ahom"),
    HATRAN(UScript.HATRAN, "Hatr"),
    MODI(UScript.MODI, "Modi"),
    MULTANI(UScript.MULTANI, "Mult"),
    PAU_CIN_HAU(UScript.PAU_CIN_HAU, "Pauc"),
    SIDDHAM(UScript.SIDDHAM, "Sidd"),
    ADLAM(UScript.ADLAM, "Adlm"),
    BHAIKSUKI(UScript.BHAIKSUKI, "Bhks"),
    MARCHEN(UScript.MARCHEN, "Marc"),
    NEWA(UScript.NEWA, "Newa"),
    OSAGE(UScript.OSAGE, "Osge"),
    HAN_WITH_BOPOMOFO(UScript.HAN_WITH_BOPOMOFO, "Hanb"),
    JAMO(UScript.JAMO, "Jamo"),
    SYMBOLS_EMOJI(UScript.SYMBOLS_EMOJI, "Zsye"),
    MASARAM_GONDI(UScript.MASARAM_GONDI, "Gonm"),
    SOYOMBO(UScript.SOYOMBO, "Soyo"),
    ZANABAZAR_SQUARE(UScript.ZANABAZAR_SQUARE, "Zanb"),
    DOGRA(UScript.DOGRA, "Dogr"),
    GUNJALA_GONDI(UScript.GUNJALA_GONDI, "Gong"),
    MAKASAR(UScript.MAKASAR, "Maka"),
    MEDEFAIDRIN(UScript.MEDEFAIDRIN, "Medf"),
    HANIFI_ROHINGYA(UScript.HANIFI_ROHINGYA, "Rohg"),
    SOGDIAN(UScript.SOGDIAN, "Sogd"),
    OLD_SOGDIAN(UScript.OLD_SOGDIAN, "Sogo"),
    ELYMAIC(UScript.ELYMAIC, "Elym"),
    NYIAKENG_PUACHUE_HMONG(UScript.NYIAKENG_PUACHUE_HMONG, "Hmnp"),
    NANDINAGARI(UScript.NANDINAGARI, "Nand"),
    WANCHO(UScript.WANCHO, "Wcho"),
    CHORASMIAN(UScript.CHORASMIAN, "Chrs"),
    DIVES_AKURU(UScript.DIVES_AKURU, "Diak"),
    KHITAN_SMALL_SCRIPT(UScript.KHITAN_SMALL_SCRIPT, "Kits"),
    YEZIDI(UScript.YEZIDI, "Yezi"),
    CYPRO_MINOAN(UScript.CYPRO_MINOAN, "Cpmn"),
    OLD_UYGHUR(UScript.OLD_UYGHUR, "Ougr"),
    TANGSA(UScript.TANGSA, "Tnsa"),
    TOTO(UScript.TOTO, "Toto"),
    VITHKUQI(UScript.VITHKUQI, "Vith"),
    KAWI(UScript.KAWI, "Kawi"),
    NAG_MUNDARI(UScript.NAG_MUNDARI, "Nagm"),
    ARABIC_NASTALIQ(UScript.ARABIC_NASTALIQ, "Aran"),
    ;

    val shortName: String get() = UScript.getShortName(icuValue)

    override val longName: String get() = UScript.getName(icuValue)

    companion object : UnicodeValueEnum.CompanionImpl<UnicodeScript>(
        enumType = UnicodeScript::class,
        icuPropertyId = UProperty.SCRIPT,
    ) {
        fun buildSetFromBitSet(bitSet: BitSet) = buildSet {
            var index = 0
            while (true) {
                val nextSetBit = bitSet.nextSetBit(index)
                if (nextSetBit < 0) break
                add(ofIcuValue(nextSetBit))
                index = nextSetBit + 1
            }
        }
    }
}
